### ISSUE TITLE
Consider using Java 9 or higher

### ISSUE THREAD

**Issue by lojzatran** [commercetools/commercetools-project-sync#12]
If you're using Java in Docker, memory params from Docker are not respected in Java 8, see https://developers.redhat.com/blog/2017/03/14/java-inside-docker/. Try to migrate to Java 9 to avoid this problem.

**Comment by lojzatran** [comment]
If staying with Java 8, you can try this command
```
# set -XX:MaxRAM to 70% of the cgroup limit
docker run --rm -m 1g openjdk:8-jdk sh -c 'exec java -XX:MaxRAM=$(( $(cat /sys/fs/cgroup/memory/memory.limit_in_bytes) * 100 / 70 )) -XX:+PrintFlagsFinal -version'
```
See: https://medium.com/adorsys/jvm-memory-settings-in-a-container-environment-64b0840e1d9e

**Comment by heshamMassoud** [comment]
Java 11 now

**Comment by butenkor** [comment]
Since openjdk 8u212 docker limits are supported out of the box.
