### ISSUE TITLE
Handle multiple values passed to the -s option

### ISSUE THREAD

**Issue by heshamMassoud** [commercetools/commercetools-project-sync#13]
### Current Behaviour
Currently, users can pass to the CLI 
```
java -jar commercetools-project-sync.jar -s types products
```

but the CLI would always process the first option only.

### Improvement
Throw an error if more than one value is passed to the `-s` option.

### Alternative Improvement
Process all the specified values, which means in the previous case it should first run the type sync and then product sync.

**Comment by ahmetoz** [comment]
Release with v3.10.0.
