### ISSUE TITLE
Consider making the timeout parameters for ctp-client customizable

### ISSUE THREAD

**Issue by ahmetoz** [commercetools/commercetools-project-sync#29]
- Current behavior:
the project sync using defaults for timeouts:

https://github.com/commercetools/commercetools-project-sync/blob/master/src/main/java/com/commercetools/project/sync/util/ClientConfigurationUtils.java#L54

- Expected behavior:

It can happen some timeout configuration on the project should be changed, also integration tests should be added for handling timeout related errors.

Check related java-sync issue for more detailed context:  https://github.com/commercetools/commercetools-sync-java/issues/208

**Comment by praveenkumarct** [comment]
This issue is fixed. The configuration part is moved to jvm-sdk library and it is reused by all the common libraries.
https://github.com/commercetools/commercetools-project-sync/pull/221
