### ISSUE TITLE
Sync of Tax Categories is not working if they contain states

### ISSUE THREAD

**Issue by jrabepixelart** [commercetools/commercetools-project-sync#298]
The Sync of Tax Categories fails if source and target project have states configured in their Tax Categories.
Once you delete the Tax Rates with states in the target project, the sync is working again and the tax rates with states are created again. But this is not a good workaround to get the syncing work :)

Sample Tax Category to reproduce the error:
`{
  "id": "3aa1c850-0d8d-4d3b-8c0d-1dde8258f0a0",
  "version": 802,
  "createdAt": "2017-08-31T13:02:06.375Z",
  "lastModifiedAt": "2021-06-18T07:56:57.487Z",
  "lastModifiedBy": {
    "clientId": "70HeAtGffhvSNULfTSJ0J9yT",
    "isPlatformClient": false
  },
  "name": "Riedel Retail Product Tax",
  "description": "Retail Taxrate for each Country/State",
  "rates": [
    {
      "name": "IN",
      "amount": 0,
      "includedInPrice": false,
      "country": "IN",
      "id": "4nsc4BCu",
      "subRates": []
    },
    {
      "name": "AU",
      "amount": 0.1,
      "includedInPrice": true,
      "country": "AU",
      "id": "yfcYkCLk",
      "subRates": []
    },
    {
      "name": "AT",
      "amount": 0.2,
      "includedInPrice": true,
      "country": "AT",
      "id": "BnejW7cN",
      "subRates": []
    },
    {
      "name": "FR",
      "amount": 0.2,
      "includedInPrice": true,
      "country": "FR",
      "id": "roGGnJlN",
      "subRates": []
    },
    {
      "name": "DE",
      "amount": 0.19,
      "includedInPrice": true,
      "country": "DE",
      "id": "IMrNsCUa",
      "subRates": []
    },
    {
      "name": "IT",
      "amount": 0.22,
      "includedInPrice": true,
      "country": "IT",
      "id": "f1BZd_OU",
      "subRates": []
    },
    {
      "name": "LI",
      "amount": 0.077,
      "includedInPrice": true,
      "country": "LI",
      "id": "wWnrgJWz",
      "subRates": []
    },
    {
      "name": "NZ",
      "amount": 0.15,
      "includedInPrice": true,
      "country": "NZ",
      "id": "r91BBsfn",
      "subRates": []
    },
    {
      "name": "CH",
      "amount": 0.077,
      "includedInPrice": true,
      "country": "CH",
      "id": "mYRGOXen",
      "subRates": []
    },
    {
      "name": "UK",
      "amount": 0.2,
      "includedInPrice": true,
      "country": "GB",
      "id": "1VZWM5E8",
      "subRates": []
    },
    {
      "name": "BE",
      "amount": 0.21,
      "includedInPrice": true,
      "country": "BE",
      "id": "As16yu1J",
      "subRates": []
    },
    {
      "name": "BU",
      "amount": 0.2,
      "includedInPrice": true,
      "country": "BG",
      "id": "Bkw5TZ7K",
      "subRates": []
    },
    {
      "name": "HR",
      "amount": 0.25,
      "includedInPrice": true,
      "country": "HR",
      "id": "IPEU7fY-",
      "subRates": []
    },
    {
      "name": "CY",
      "amount": 0.19,
      "includedInPrice": true,
      "country": "CY",
      "id": "l3H_7_cS",
      "subRates": []
    },
    {
      "name": "CZ",
      "amount": 0.21,
      "includedInPrice": true,
      "country": "CZ",
      "id": "u8qClFlB",
      "subRates": []
    },
    {
      "name": "DK",
      "amount": 0.25,
      "includedInPrice": true,
      "country": "DK",
      "id": "VM34yGmw",
      "subRates": []
    },
    {
      "name": "ET",
      "amount": 0.2,
      "includedInPrice": true,
      "country": "EE",
      "id": "ieZfMcRI",
      "subRates": []
    },
    {
      "name": "FI",
      "amount": 0.24,
      "includedInPrice": true,
      "country": "FI",
      "id": "98xrn4RY",
      "subRates": []
    },
    {
      "name": "GR",
      "amount": 0.24,
      "includedInPrice": true,
      "country": "GR",
      "id": "z8aFuDUB",
      "subRates": []
    },
    {
      "name": "HU",
      "amount": 0.27,
      "includedInPrice": true,
      "country": "HU",
      "id": "DMlQvnsZ",
      "subRates": []
    },
    {
      "name": "IE",
      "amount": 0.23,
      "includedInPrice": true,
      "country": "IE",
      "id": "KGQhJm1p",
      "subRates": []
    },
    {
      "name": "LT",
      "amount": 0.21,
      "includedInPrice": true,
      "country": "LV",
      "id": "pLZTISYC",
      "subRates": []
    },
    {
      "name": "LV",
      "amount": 0.21,
      "includedInPrice": true,
      "country": "LT",
      "id": "aFKwLvjN",
      "subRates": []
    },
    {
      "name": "LU",
      "amount": 0.17,
      "includedInPrice": true,
      "country": "LU",
      "id": "FqrT5OWD",
      "subRates": []
    },
    {
      "name": "MA",
      "amount": 0.18,
      "includedInPrice": true,
      "country": "MT",
      "id": "S7Rd1h1B",
      "subRates": []
    },
    {
      "name": "NL",
      "amount": 0.19,
      "includedInPrice": true,
      "country": "NL",
      "id": "KzbElsJQ",
      "subRates": []
    },
    {
      "name": "NO",
      "amount": 0,
      "includedInPrice": false,
      "country": "NO",
      "id": "yez4urfj",
      "subRates": []
    },
    {
      "name": "PO",
      "amount": 0.23,
      "includedInPrice": true,
      "country": "PL",
      "id": "Zi4p52F8",
      "subRates": []
    },
    {
      "name": "PT",
      "amount": 0.23,
      "includedInPrice": true,
      "country": "PT",
      "id": "REl-B2Bi",
      "subRates": []
    },
    {
      "name": "RO",
      "amount": 0.2,
      "includedInPrice": true,
      "country": "RO",
      "id": "3VMI7BFF",
      "subRates": []
    },
    {
      "name": "SV",
      "amount": 0.2,
      "includedInPrice": true,
      "country": "SK",
      "id": "a8WQPbFa",
      "subRates": []
    },
    {
      "name": "SL",
      "amount": 0.22,
      "includedInPrice": true,
      "country": "SI",
      "id": "j3tZoy6-",
      "subRates": []
    },
    {
      "name": "ES",
      "amount": 0.21,
      "includedInPrice": true,
      "country": "ES",
      "id": "FB8qDQU-",
      "subRates": []
    },
    {
      "name": "VA",
      "amount": 0.22,
      "includedInPrice": true,
      "country": "VA",
      "id": "0A5t4a_Z",
      "subRates": []
    },
    {
      "name": "CA",
      "amount": 0.05,
      "includedInPrice": false,
      "country": "CA",
      "state": "AB",
      "id": "sieN0vc2",
      "subRates": []
    },
    {
      "name": "SE",
      "amount": 0.25,
      "includedInPrice": true,
      "country": "SE",
      "id": "6zXhsBU9",
      "subRates": []
    },
    {
      "name": "MC",
      "amount": 0.2,
      "includedInPrice": true,
      "country": "MC",
      "id": "nfmOQZUT",
      "subRates": []
    },
    {
      "name": "IS",
      "amount": 0,
      "includedInPrice": false,
      "country": "IS",
      "id": "x4CivvTO",
      "subRates": []
    },
    {
      "name": "CA",
      "amount": 0.12,
      "includedInPrice": false,
      "country": "CA",
      "state": "BC",
      "id": "lumlF5eB",
      "subRates": []
    },
    {
      "name": "CA",
      "amount": 0.12,
      "includedInPrice": false,
      "country": "CA",
      "state": "MB",
      "id": "wlKQ9UmF",
      "subRates": []
    },
    {
      "name": "CA",
      "amount": 0.15,
      "includedInPrice": false,
      "country": "CA",
      "state": "NB",
      "id": "RSjcfPpD",
      "subRates": []
    },
    {
      "name": "CA",
      "amount": 0.15,
      "includedInPrice": false,
      "country": "CA",
      "state": "NL",
      "id": "nHv5l25H",
      "subRates": []
    },
    {
      "name": "CA",
      "amount": 0.15,
      "includedInPrice": false,
      "country": "CA",
      "state": "NS",
      "id": "hvUnuZDm",
      "subRates": []
    },
    {
      "name": "CA",
      "amount": 0.05,
      "includedInPrice": false,
      "country": "CA",
      "state": "NT",
      "id": "-lz_opHC",
      "subRates": []
    },
    {
      "name": "CA",
      "amount": 0.05,
      "includedInPrice": false,
      "country": "CA",
      "state": "NU",
      "id": "BDvCDkz6",
      "subRates": []
    },
    {
      "name": "CA",
      "amount": 0.13,
      "includedInPrice": false,
      "country": "CA",
      "state": "ON",
      "id": "XD3WEpLB",
      "subRates": []
    },
    {
      "name": "CA",
      "amount": 0.15,
      "includedInPrice": false,
      "country": "CA",
      "state": "PE",
      "id": "_p2OSrAr",
      "subRates": []
    },
    {
      "name": "CA",
      "amount": 0.14975,
      "includedInPrice": false,
      "country": "CA",
      "state": "QC",
      "id": "NU4V3gyd",
      "subRates": []
    },
    {
      "name": "CA",
      "amount": 0.11,
      "includedInPrice": false,
      "country": "CA",
      "state": "SK",
      "id": "3P5jthul",
      "subRates": []
    },
    {
      "name": "CA",
      "amount": 0.05,
      "includedInPrice": false,
      "country": "CA",
      "state": "YT",
      "id": "5fkLvA6-",
      "subRates": []
    },
    {
      "name": "AE",
      "amount": 0,
      "includedInPrice": true,
      "country": "AE",
      "id": "LS_QwRGU",
      "subRates": []
    },
    {
      "name": "AU",
      "amount": 0.1,
      "includedInPrice": true,
      "country": "AU",
      "state": "NSW",
      "id": "vi8p19Cv",
      "subRates": []
    },
    {
      "name": "AU",
      "amount": 0.1,
      "includedInPrice": true,
      "country": "AU",
      "state": "QLD",
      "id": "WYYowrVn",
      "subRates": []
    },
    {
      "name": "AU",
      "amount": 0.1,
      "includedInPrice": true,
      "country": "AU",
      "state": "SA",
      "id": "6QGXBZm2",
      "subRates": []
    },
    {
      "name": "AU",
      "amount": 0.1,
      "includedInPrice": true,
      "country": "AU",
      "state": "TAS",
      "id": "-iKhtfrV",
      "subRates": []
    },
    {
      "name": "AU",
      "amount": 0.1,
      "includedInPrice": true,
      "country": "AU",
      "state": "VIC",
      "id": "0wPwvJRb",
      "subRates": []
    },
    {
      "name": "AU",
      "amount": 0.1,
      "includedInPrice": true,
      "country": "AU",
      "state": "WA",
      "id": "7xyTsLmN",
      "subRates": []
    },
    {
      "name": "AU",
      "amount": 0.1,
      "includedInPrice": true,
      "country": "AU",
      "state": "ACT",
      "id": "kmVcnx0N",
      "subRates": []
    },
    {
      "name": "AU",
      "amount": 0.1,
      "includedInPrice": true,
      "country": "AU",
      "state": "NT",
      "id": "zP1-yP4_",
      "subRates": []
    },
    {
      "name": "GB",
      "amount": 0,
      "includedInPrice": false,
      "country": "GB",
      "state": "JE",
      "id": "fELfR8OJ",
      "subRates": []
    },
    {
      "name": "GB",
      "amount": 0,
      "includedInPrice": false,
      "country": "GB",
      "state": "GG",
      "id": "q8k-_m2U",
      "subRates": []
    }
  ],
  "key": "standardRetailProduct"
}`

Used Docker Command:

`docker run -e SOURCE_PROJECT_KEY=riedel-main-stage -e SOURCE_CLIENT_ID=xxx-0RXp -e SOURCE_CLIENT_SECRET=xxx -e TARGET_PROJECT_KEY=riedel-dev -e TARGET_CLIENT_ID=xxx -e
TARGET_CLIENT_SECRET=xxx commercetools/commercetools-project-sync:4.0.3 -s taxCategories
{"timestamp":"2021-06-18T07:50:41.636Z","severity":"INFO","loggerName":"com.commercetools.project.sync.taxcategory.TaxCategorySyncer","message":"Starting TaxCategorySync from CTP project with key 'riedel-main-stage' to project with ke
y 'riedel-dev'"}
{"timestamp":"2021-06-18T07:50:43.257Z","severity":"ERROR","loggerName":"com.commercetools.project.sync.taxcategory.TaxCategorySyncer","message":"Error when trying to sync tax category. Existing key: standardRetailProduct. Update acti
ons: ReplaceTaxRate[taxRate=TaxRateDraftImpl[amount=0.05,country=CA,includedInPrice=false,name=CA,state=AB,subRates=[]],taxRateId=ScOM3b5y,action=replaceTaxRate],ReplaceTaxRate[taxRate=TaxRateDraftImpl[amount=0.1,country=AU,includedIn
Price=true,name=AU,state=<null>,subRates=[]],taxRateId=rn63Bxf4,action=replaceTaxRate],AddTaxRate[taxRate=TaxRateDraftImpl[amount=0.0,country=GB,includedInPrice=false,name=GB,state=JE,subRates=[]],action=addTaxRate],AddTaxRate[taxRate
=TaxRateDraftImpl[amount=0.0,country=GB,includedInPrice=false,name=GB,state=GG,subRates=[]],action=addTaxRate]","stackHash":"c408fba9","stackTrace":"i.s.s.c.ErrorResponseException: detailMessage: A duplicate value '{\"country\":\"CA\"
,\"state\":\"AB\"}' exists for field 'country'.\nsummary: POST https://api.europe-west1.gcp.commercetools.com/riedel-dev/tax-categories/3aa1c850-0d8d-4d3b-8c0d-1dde8258f0a0 failed  with response code 400 with X-Correlation-ID `riedel-
dev/909e544a-4394-4ccb-92c5-85a8266d2eb2` on 2021-06-18T07:50:43.138337Z\nhttp response formatted body: {\n  \"statusCode\" : 400,\n  \"message\" : \"A duplicate value '{\\\"country\\\":\\\"CA\\\",\\\"state\\\":\\\"AB\\\"}' exists for
 field 'country'.\",\n  \"errors\" : [ {\n    \"code\" : \"DuplicateField\",\n    \"message\" : \"A duplicate value '{\\\"country\\\":\\\"CA\\\",\\\"state\\\":\\\"AB\\\"}' exists for field 'country'.\",\n    \"action\" : {\n      \"ac
tion\" : \"replaceTaxRate\",\n      \"taxRateId\" : \"ScOM3b5y\",\n      \"taxRate\" : {\n        \"name\" : \"CA\",\n        \"amount\" : 0.05,\n        \"includedInPrice\" : false,\n        \"country\" : \"CA\",\n        \"state\" :
 \"AB\",\n        \"subRates\" : [ ]\n      }\n    },\n    \"actionIndex\" : 1,\n    \"duplicateValue\" : {\n      \"country\" : \"CA\",\n      \"state\" : \"AB\"\n    },\n    \"field\" : \"country\"\n  } ]\n}\nhttp response: io.spher
e.sdk.http.HttpResponseImpl@74024d7a[statusCode=400,headers={date=[Fri, 18 Jun 2021 07:50:38 GMT], content-length=[496], server=[istio-envoy], x-envoy-upstream-service-time=[9], Alt-Svc=[clear], access-control-allow-headers=[Accept, A
uthorization, Content-Type, Origin, User-Agent, X-Correlation-ID], x-correlation-id=[riedel-dev/909e544a-4394-4ccb-92c5-85a8266d2eb2], x-http-status-caused-by-extension=[false], access-control-allow-methods=[GET, POST, DELETE, OPTIONS
], Via=[1.1 google], access-control-allow-origin=[*], access-control-max-age=[299], content-type=[application/json; charset=utf-8], server-timing=[projects;dur=8]},associatedRequest=<null>,textInterpretedBody={\"statusCode\":400,\"mes
sage\":\"A duplicate value '{\\\"country\\\":\\\"CA\\\",\\\"state\\\":\\\"AB\\\"}' exists for field 'country'.\",\"errors\":[{\"code\":\"DuplicateField\",\"message\":\"A duplicate value '{\\\"country\\\":\\\"CA\\\",\\\"state\\\":\\\"A
B\\\"}' exists for field 'coun...\n"}
{"timestamp":"2021-06-18T07:50:43.307Z","severity":"INFO","loggerName":"com.commercetools.project.sync.taxcategory.TaxCategorySyncer","message":"Summary: 1 tax categories were processed in total (0 created, 0 updated and 1 failed to s
ync).","statistics":{"updated":0,"created":0,"failed":1,"processed":1,"latestBatchProcessingTimeInDays":0,"latestBatchProcessingTimeInHours":0,"latestBatchProcessingTimeInMinutes":0,"latestBatchProcessingTimeInSeconds":0,"latestBatchP
rocessingTimeInMillis":276,"latestBatchHumanReadableProcessingTime":"0d, 0h, 0m, 0s, 276ms","reportMessage":"Summary: 1 tax categories were processed in total (0 created, 0 updated and 1 failed to sync)."}}`

**Comment by ahmetoz** [comment]
Hi @jrabepixelart thanks for opening issue and letting us know. 
I also faced similar issue on sync, related to country code, the platform returns. A duplicate value '...' exists for field 'country'`. It works when the target project is empty but has some issues on update cases as above. 
I will put this issue into our backlog and we will investigate on the topic.

**Comment by praveenkumarct** [comment]
This issue is fixed and published. Fo release notes check [4.0.4](https://github.com/commercetools/commercetools-project-sync/releases/tag/4.0.4).
