### ISSUE TITLE
Inventory Sync fails because of a duplicate?!

### ISSUE THREAD

**Issue by markus-mw** [commercetools/commercetools-project-sync#301]
We have a multi channel setup and I'm trying to sync between production and staging system. The issue I always get (no matter if full or delta) is, that there is a duplicate value for the sku. Am I wrong or isn't it normal, that we have multiple inventory channels if there are mutliple channels? So why do I get this kind of error?

`
{"timestamp":"2021-06-23T10:37:16.927Z","severity":"ERROR","loggerName":"com.commercetools.project.sync.inventoryentry.InventoryEntrySyncer","message":"Error when trying to sync inventory entry. Existing key: <<not present>>. Update actions: []","stackHash":"e8fa2b3c","stackTrace":"i.s.s.c.ErrorResponseException: detailMessage: A duplicate value '\"5299\"' exists for field 'sku'.
summary: POST https://api.europe-west1.gcp.commercetools.com/[project-id]/inventory failed  with response code 400 with X-Correlation-ID `[project-id]/b8ccdd76-2c53-4b93-828a-781e9bd0ad84` on 2021-06-23T10:37:16.899508Z
http response formatted body: {
  \"statusCode\" : 400,
  \"message\" : \"A duplicate value '\\\"5299\\\"' exists for field 'sku'.\",
  \"errors\" : [ {
    \"code\" : \"DuplicateField\",
    \"message\" : \"A duplicate value '\\\"5299\\\"' exists for field 'sku'.\",
    \"duplicateValue\" : \"5299\",
    \"field\" : \"sku\"
  } ]
}
http response: io.sphere.sdk.http.HttpResponseImpl@5fe04fb3[statusCode=400,headers={date=[Wed, 23 Jun 2021 10:37:16 GMT], content-length=[223], server=[istio-envoy], x-envoy-upstream-service-time=[8], Alt-Svc=[clear], access-control-allow-headers=[Accept, Authorization, Content-Type, Origin, User-Agent, X-Correlation-ID], x-correlation-id=[[project-id]/b8ccdd76-2c53-4b93-828a-781e9bd0ad84], x-http-status-caused-by-extension=[false], access-control-allow-methods=[GET, POST, DELETE, OPTIONS], Via=[1.1 google], access-control-allow-origin=[*], access-control-max-age=[299], content-type=[application/json; charset=utf-8], server-timing=[projects;dur=6]},associatedRequest=<null>,textInterpretedBody={\"statusCode\":400,\"message\":\"A duplicate value '\\\"5299\\\"' exists for field 'sku'.\",\"errors\":[{\"code\":\"DuplicateField\",\"message\":\"A duplicate value '\\\"5299\\\"' exists for field 'sku'.\",\"duplicateValue\":\"5299\",\"field\":\"sku\"}]}]
SDK: 1.63.0
project: [project-id]
endpoint: POST /inventory
Java: 11.0.11
cwd: /app
sphere request: InventoryEntryCreateCommandImpl[body=InventoryEntryDraftDsl[custom=<null>,expectedDelivery=<null>,quantityOnStock=0,restockableInDays=<null>,sku=5299,supplyChannel=<null>],creationFunction=io.sphere.sdk.inventory.commands.InventoryEntryCreateCommandImpl$$Lambda$830/0x00000008004cd440@1606666e,endpoint=/inventory,expansionModel=InventoryEntryExpansionModelImpl[pathExpressions=[]],expansionP...
"}
`

**Comment by butenkor** [comment]
Hi @markus-mw, you can create 2 inventories with the same SKU only if they they have different channels assigned. In the request above I do not see `supplyChannel` provided, so this might be your issue? Here is the doc which describes how channels has to be supplied: https://github.com/commercetools/commercetools-sync-java/blob/master/docs/usage/INVENTORY_SYNC.md#reference-resolution

**Comment by markus-mw** [comment]
@butenkor : The inventory entries seem to be fine. There are 2 inventory entries with sku == 5299. One of them has no supplyChannel, the other one has one.

The request from above is from your sync tool. I don't do any custom thins here. Its just the sync I do:
`...commercetools/commercetools-project-sync:4.0.3 -t inventoryEntries`

**Comment by butenkor** [comment]
In order to reproduce the issue could you please provide JSON snippets of:
- All existing inventory entries in the target project with the SKU=5299
- All existing inventory entries in the source project with the SKU=5299

**Comment by markus-mw** [comment]
Source:
`
{
  "limit": 20,
  "offset": 0,
  "count": 2,
  "total": 2,
  "results": [
    {
      "id": "000e3540-8775-43fc-83e2-16a43ccefade",
      "version": 1,
      "lastMessageSequenceNumber": 1,
      "createdAt": "2021-05-03T07:50:02.636Z",
      "lastModifiedAt": "2021-05-03T07:50:02.636Z",
      "lastModifiedBy": {
        "clientId": "gr2xWkclv3R6S7YCwZSCVamg",
        "isPlatformClient": false
      },
      "createdBy": {
        "clientId": "gr2xWkclv3R6S7YCwZSCVamg",
        "isPlatformClient": false
      },
      "sku": "5299",
      "quantityOnStock": 0,
      "availableQuantity": 0,
      "reservations": []
    },
    {
      "id": "771d44b4-3e9a-42b3-a5f3-a6d9f6f517aa",
      "version": 3,
      "lastMessageSequenceNumber": 1,
      "createdAt": "2021-05-06T14:20:35.395Z",
      "lastModifiedAt": "2021-05-06T14:20:35.435Z",
      "lastModifiedBy": {
        "clientId": "gr2xWkclv3R6S7YCwZSCVamg",
        "isPlatformClient": false
      },
      "createdBy": {
        "clientId": "gr2xWkclv3R6S7YCwZSCVamg",
        "isPlatformClient": false
      },
      "sku": "5299",
      "supplyChannel": {
        "typeId": "channel",
        "id": "a3f63ce3-74ce-48e7-9323-f7d2bcdd4449"
      },
      "quantityOnStock": 0,
      "availableQuantity": 0,
      "reservations": [],
      "custom": {
        "type": {
          "typeId": "type",
          "id": "211d067e-7b7a-4bde-9121-1070aa83b2fe"
        },
        "fields": {
          "merchant_article_nr": "25752"
        }
      }
    }
  ]
}
`

Target:
`
{
  "limit": 20,
  "offset": 0,
  "count": 2,
  "total": 2,
  "results": [
    {
      "id": "fb6fdbb0-eac9-4ffb-b389-07c75236ff97",
      "version": 1,
      "lastMessageSequenceNumber": 1,
      "createdAt": "2021-05-06T11:56:18.481Z",
      "lastModifiedAt": "2021-05-06T11:56:18.481Z",
      "lastModifiedBy": {
        "clientId": "7vcz_Ndp0xGftXRsGxt8H3gn",
        "isPlatformClient": false
      },
      "createdBy": {
        "clientId": "7vcz_Ndp0xGftXRsGxt8H3gn",
        "isPlatformClient": false
      },
      "sku": "5299",
      "quantityOnStock": 0,
      "availableQuantity": 0,
      "reservations": []
    },
    {
      "id": "79664a98-0600-4143-9e89-48f61591de88",
      "version": 1,
      "lastMessageSequenceNumber": 1,
      "createdAt": "2021-06-28T11:19:04.199Z",
      "lastModifiedAt": "2021-06-28T11:19:04.199Z",
      "lastModifiedBy": {
        "clientId": "7vcz_Ndp0xGftXRsGxt8H3gn",
        "isPlatformClient": false
      },
      "createdBy": {
        "clientId": "7vcz_Ndp0xGftXRsGxt8H3gn",
        "isPlatformClient": false
      },
      "sku": "5299",
      "supplyChannel": {
        "typeId": "channel",
        "id": "699f2a0c-f141-495f-96f7-6c067f0fd2bc"
      },
      "quantityOnStock": 0,
      "availableQuantity": 0,
      "reservations": [],
      "custom": {
        "type": {
          "typeId": "type",
          "id": "fad7c068-35c8-4ff0-8296-30b28c962696"
        },
        "fields": {
          "merchant_article_nr": "25752"
        }
      }
    }
  ]
}
`

**Comment by butenkor** [comment]
The inventories you provided seem to be the same in both source and target so I would expect the project sync not to create or update anything. Did you fix it manually in the target project or the above state causes the sync to always create a new duplicate inventory?

**Comment by markus-mw** [comment]
I didn't fixed anything manual. Im just running the command from above. Please note, that I always do the full-sync and no delta. 
I guess that the sync is working, but the errors should be suppressed.

**Comment by butenkor** [comment]
Ok, thanks for all the infos. We will try to reproduce and fix it.

**Comment by butenkor** [comment]
@markus-mw Unfortunately we were not able to reproduce the issue with your examples. Are you able to provide us with a reproducible example/setup?

**Comment by butenkor** [comment]
One more thing worthy to check is that you might run into race conditions since the inventory with ID `771d44b4-3e9a-42b3-a5f3-a6d9f6f517aa` has version 3 and looking at its `createdAt` and `lastModifiedAt` dates means that is has been created and updated with 2-3 separate requests and all of it within just 40ms! So many requests in such a short time looks like concurrent processes changing the same data which you should avoid if you want to omit eventual side effects.

**Comment by markus-mw** [comment]
@butenkor : These projects don't have that much traffic, so that it would be a big coincidence. The only way to give you a reproduceable example or setup would be, if you run the docker container with my customers two projects.
I think I'll create a support ticket with a reference to this issue here, so that I can give one of your colleagues the credentials.

**Comment by butenkor** [comment]
@markus-mw we were able to reproduce the issue with the help of the support ticket you created. We will probably fix it until 23 of July since we have started our sprint already. I hope this timing if fine for you.

**Comment by ahmetoz** [comment]
Hi @markus-mw sorry for the waiting for that long, also thanks for the opening this issue that we haven't aware until now 💯 

I've just released a new version of this project, you might evaluate the version 4.0.5, https://github.com/commercetools/commercetools-project-sync/releases/tag/4.0.5 please let us know if you encounter issues on inventory sync after that change 🙏🏽
