### ISSUE TITLE
Syncing state with no transitions configured leads to empty transition-array at the destination

### ISSUE THREAD

**Issue by liquidsunset** [commercetools/commercetools-project-sync#321]
When syncing states without any transitions configured (in our case null, using java),
the transition is set as empty array in the destination project.

We would expect that the transition field is null and not an  empty array as in the source state.

**Comment by praveenkumarct** [comment]
@liquidsunset Thank you. We have added this into backlog. Will update you once it is fixed and released soon.

**Comment by praveenkumarct** [comment]
We have fixed the issue and released it. [Release notes](https://github.com/commercetools/commercetools-project-sync/releases/tag/4.0.9)
