### ISSUE TITLE
Problem with delta sync 

### ISSUE THREAD

**Issue by heshamMassoud** [commercetools/commercetools-project-sync#33]
The generated time stamp is persisted with the buffer (-2 minutes) which is wrong. 

Only when querying from modified resources we should query using the -2 minutes buffer.

**Comment by butenkor** [comment]
> The generated time stamp is persisted with the buffer (-2 minutes) which is wrong.
Only when querying from modified resources we should query using the -2 minutes buffer.

@heshamMassoud Why is it wrong and what is the difference between 2 approaches?  

> The generated time stamp is persisted with the buffer (-2 minutes)

This seems correct.

**Comment by heshamMassoud** [comment]
https://github.com/commercetools/commercetools-project-sync/pull/35

**Comment by heshamMassoud** [comment]
released in `3.2.0`
