### ISSUE TITLE
[Hacktoberfest] Use the concurrency keyword to limit the concurrency of the github action's workflow run. 

### ISSUE THREAD

**Issue by ahmetoz** [commercetools/commercetools-project-sync#331]
**Situation**
To limit the github action workflow concurrency we are using a github action step from https://github.com/softprops/turnstyle
https://github.com/commercetools/commercetools-project-sync/blob/90bfbfa11d07ae3d7e017d57da815cafaa96f0d5/.github/workflows/ci.yml#L13-L20
> This is needed because running build in parallel causing data conflicts related to the integration tests.

**Complication**
While we are building the first action flow, github was not supporting this feature, but now seems github introduced `concurrency` keyword to limit the concurrency in the action.
See: https://github.blog/changelog/2021-04-19-github-actions-limit-workflow-run-or-job-concurrency/

**Resolution**
Use the `concurrency` keyword to limit the concurrency of the workflow run.

> Ensure you have changed all workflows in the folder: https://github.com/commercetools/commercetools-project-sync/tree/master/.github/workflows

[CONTRIBUTING](https://github.com/commercetools/commercetools-project-sync/blob/master/docs/CONTRIBUTING.md)

**Comment by HollowMan6** [comment]
Hi, I've submitted PR #339 for this PR, but I wonder what this means:
> Ensure you have changed all workflows in the folder: https://github.com/commercetools/commercetools-project-sync/tree/master/.github/workflows

since I find only the ci workflow uses turnstyle. If you need concurrency for all workflows instead of only ci, please tell me and I will add it for all.
