### ISSUE TITLE
[Hacktoberfest] Collect release notes in to a RELEASE_NOTES markdown file.

### ISSUE THREAD

**Issue by ahmetoz** [commercetools/commercetools-project-sync#334]
**Situation**
The release notes documented only in the release section of the repository.

**Complication**
Current release notes is not searchable and not easy to navigate.

**Resolution**
Collect previous release notes in a RELEASE_NOTES markdown file.

**Comment by jhanna60** [comment]
Hey can I be assigned this one please?

**Comment by ahmetoz** [comment]
Hey @jhanna60 feel free to contribute 😊👍

**Comment by jhanna60** [comment]
Thanks a lot, quick question as well please, you mention you want this named RELEASE_NOTES, in the past I have done similar in repos and we referred to it as ChangeLog.md. Happy to do either way whatever you prefer?

**Comment by ahmetoz** [comment]
Hey @jhanna60 I would rather use RELEASE_NOTES.md, one example from another project of ours maybe could give some idea: https://github.com/commercetools/commercetools-sync-java/blob/master/docs/RELEASE_NOTES.md

**Comment by jhanna60** [comment]
Ah ok thanks, this info would have been great in the original ticket :) . I have finished this task now but I've done it using the styling as laid out by this standard - https://keepachangelog.com/en/1.0.0/ 

I will go back and add some extra things to make it more in line with what you sent in your other link

**Comment by ahmetoz** [comment]
Hey @jhanna60 no worries, I was not aware of the changelog that you shared and but good to know, here you don't need to follow the ideas in the shared link, just shared it to give some example what I did before 😬, maybe keep as you did, then we would learn from it and we could adjust it based on the code review phase. Thanks 🙏

**Comment by jhanna60** [comment]
No problem thanks for being so flexible, I have however went back now and modified it to better reflect the standard Setout in your other projects. Perhaps in future we can update them all at the same time if we wish to introduce some more standards into them :) ?

**Comment by ahmetoz** [comment]
Why not 😄 if there is a standard it's better to follow them not, I will check the link that you shared in detail, appreciated 👍🏽 
 also looking forward to see the changelog/release notes document ^^

**Comment by jhanna60** [comment]
Ok that's the PR lodged now, hopefully its what you were after. Let me know either way 👍
