### ISSUE TITLE
missing support for channels is impacting products sync

### ISSUE THREAD

**Issue by srinivasbellarichenna** [commercetools/commercetools-project-sync#345]
Hello,

In our case product variant's price is associated with channel. 
The current application is not supporting the channels sync. Hence, the product sync is failing while looking for non-existing channel references on that target project.

May I know if you are having this support of channels already on the roadmap? If not, how do you recommend tackling this issue?

Thanks,
Srini

**Comment by praveenkumarct** [comment]
@srinivasbellarichenna 
As discussed in the support ticket, We are waiting for your PR.

Thanks.

**Comment by lojzatran** [comment]
Closing this ticket due to its inactivity. Also there is a new duplicate ticket: https://github.com/commercetools/commercetools-project-sync/issues/463
