### ISSUE TITLE
java.util.concurrent.CompletionException: io.sphere.sdk.client.InvalidClientCredentialsException: detailMessage: Invalid credentials for <project-key> on https://auth.sphere.io

### ISSUE THREAD

**Issue by adhikariarjun21** [commercetools/commercetools-project-sync#36]
The auth URL used here is https://auth.sphere.io. Can we have it to use the United states URL(https://auth.commercetools.co/) ?

**Comment by heshamMassoud** [comment]
Hi @adhikariarjun21,

Indeed the client's configuration uses by default the `https://auth.sphere.io` url. To add extra configuration to your client more than the basic project credentials documented [here](https://github.com/commercetools/commercetools-project-sync#prerequisites), you can set the following environment variables: 

````bash
export SOURCE_AUTH_URL="https://auth.commercetools.co/"
export SOURCE_API_URL="https://api.commercetools.co/"
export SOURCE_SCOPES="manage_project" #optional parameter
#separate multiple elements with a comma
#export SOURCE_SCOPES="manage_customers,view_orders"
````
_(P.S. Only the source project is used for the above example. For the target project, replace `SOURCE_` with `TARGET_` in the env variable name, e.g. `TARGET_AUTH_URL`._

**Comment by heshamMassoud** [comment]
This should have been documented in the README of this repository.

**Comment by heshamMassoud** [comment]
now it is added to the documentation: https://github.com/commercetools/commercetools-project-sync#prerequisites

**Comment by adhikariarjun21** [comment]
Thanks @heshamMassoud
