### ISSUE TITLE
Customer Groups are not being synced

### ISSUE THREAD

**Issue by sfernengel** [commercetools/commercetools-project-sync#377]
When syncing customers, if the customer group a customer belongs to does not exist on the target project, the operation fails

**Comment by praveenkumarct** [comment]
Hello @sfernengel,

As detailed in the documentation [here](https://github.com/commercetools/commercetools-project-sync#what-is-this) , we don't yet support CustomerGroups sync in this application. You can add customer group in target and then sync customer.

**Comment by sfernengel** [comment]
Hi @lojzatran, I don't have any further questions.
