### ISSUE TITLE
Support for ARM images

### ISSUE THREAD

**Issue by drpayyne** [commercetools/commercetools-project-sync#388]
Hello, I noticed that the Docker images published are only for amd64 and not arm64. Are there any plans to publish these images for arm64 chips as well? (This is for all the new Apple chips)

**Comment by praveenkumarct** [comment]
Hello @drpayyne, 
We will work on this and publish it in coming weeks.
Thanks.

**Comment by lojzatran** [comment]
Hello @drpayyne 

We are now creating docker images also for arm64. See our new release: https://github.com/commercetools/commercetools-project-sync/releases/tag/5.2.0.

I'm closing this issue. If there are any problems, feel free to comment on it or reopen.
