### ISSUE TITLE
ProductDiscounts Sync Feature Request

### ISSUE THREAD

**Issue by voroshkov** [commercetools/commercetools-project-sync#455]
Currently the tool does not support synchronizing Product Discounts.
Are there any plans to extend the tool functionality to also cover Product Discounts or are there any other means of automating this process?

**Comment by anjaliVashisth** [comment]
Hi @voroshkov, 
Thank you for reaching out. 
Yes, we don't provide the support for Product discounts at the moment. 
However, please feel free to create a support ticket for adding the support of Product Discounts here, https://support.commercetools.com/
Thank you.

**Comment by salander85** [comment]
Hi @voroshkov ,
do you still need support on this topic? If not, please close the issue.
Thanks.

**Comment by lojzatran** [comment]
I'm closing this topic as the feature should be requested in the support portal.

**Comment by lojzatran** [comment]
I'm closing this topic as the feature should be requested in the support portal.
