### ISSUE TITLE
stores and channels sync

### ISSUE THREAD

**Issue by Amenocy** [commercetools/commercetools-project-sync#463]
Hi, 

syncing channels (and stores) are essential because they are referenced in inventory entries.
please give priority to them.

**Comment by lojzatran** [comment]
Hi @Amenocy,

Thank you for reaching out.
Yes, we don't provide the support for Channels and Stores at the moment.
However, please feel free to create a support ticket for adding the support of Channels and Stores here: https://support.commercetools.com/

Thank you.

**Comment by lojzatran** [comment]
I'm hereby closing this issue.
