### ISSUE TITLE
Project sync is failing to sync products having Set on reference attribute

### ISSUE THREAD

**Issue by pramit-adhikari** [commercetools/commercetools-project-sync#478]
Project sync is failing to sync products for product having set operation of reference attribute. 
Getting below error
`{"timestamp":"2023-08-18T19:30:08.166Z","severity":"INFO","loggerName":"com.commercetools.project.sync.product.ProductSyncer","message":"Starting ProductSync from CTP project with key 'abbott-lingo-eu-dev-001' to project with key 'lingo-us-dev'"}
Aug 18, 2023 7:30:09 PM org.javamoney.moneta.DefaultMonetaryContextFactory createContextWithConfig
INFO: Using default MathContext.DECIMAL64
{"timestamp":"2023-08-18T19:30:09.882Z","severity":"WARN","loggerName":"com.commercetools.project.sync.product.ProductSyncer","message":"java.lang.NullPointerException","stackHash":"b904a893","stackTrace":"j.l.NullPointerException: null\n\tat j.u.c.ConcurrentHashMap.get(Unknown Source)\n\tat c.g.b.c.c.BoundedLocalCache.getIfPresent(BoundedLocalCache.java:2058)\n\tat c.g.b.c.c.LocalManualCache.getIfPresent(LocalManualCache.java:56)\n\tat c.c.s.c.u.CaffeineReferenceIdToKeyCacheImpl.containsKey(CaffeineReferenceIdToKeyCacheImpl.java:42)\n\tat c.c.s.c.u.SyncUtils.getReferenceWithKeyReplaced(SyncUtils.java:61)\n\tat c.c.s.p.u.VariantReferenceResolutionUtils.lambda$replaceAttributeReferenceSetIdsWithKeys$11(VariantReferenceResolutionUtils.java:210)\n\tat j.u.s.ReferencePipeline$3$1.accept(Unknown Source)\n\tat java.util.Iterator.forEachRemaining(Unknown Source)\n\tat j.u.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)\n\tat j.u.s.AbstractPipeline.copyInto(Unknown Source)\n\tat j.u.s.AbstractPipeline.wrapAndCopyInto(Unknown Source)\n\tat j.u.s.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)\n\tat j.u.s.AbstractPipeline.evaluate(Unknown Source)\n\tat j.u.s.ReferencePipeline.collect(Unknown Source)\n\tat c.c.s.p.u.VariantReferenceResolutionUtils.lambda$replaceAttributeReferenceSetIdsWithKeys$12(VariantReferenceResolutionUtils.java:216)\n\tat java.util.Optional.map(Unknown Source)\n\tat c.c.s.p.u.VariantReferenceResolutionUtils.replaceAttributeReferenceSetIdsWithKeys(VariantReferenceResolutionUtils.java:205)\n\tat c.c.s.p.u.VariantReferenceResolutionUtils.lambda$replaceAttributesReferencesIdsWithKeys$5(VariantReferenceResolutionUtils.java:165)\n\tat java.util.Optional.orElseGet(Unknown Source)\n\tat c.c.s.p.u.VariantReferenceResolutionUtils.lambda$replaceAttributesReferencesIdsWithKeys$6(VariantReferenceResolutionUtils.java:163)\n\tat j.u.s.ReferencePipeline$3$1.accept(Unknown Source)\n\tat j.u.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)\n\tat j.u.s.AbstractPipeline.copyInto(Unknown Source)\n\tat j.u.s.AbstractPipeline.wrapAndCopyInto(Unknown Source)\n\tat j.u.s.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)\n\tat j.u.s.AbstractPipeline.evaluate(Unknown Source)\n\tat j.u.s.ReferencePipeline.collect(Unknown Source)\n\tat c.c.s...\n"}
{"timestamp":"2023-08-18T19:30:09.897Z","severity":"INFO","loggerName":"com.commercetools.project.sync.product.ProductSyncer","message":"Summary: 0 product(s) were processed in total (0 created, 0 updated, 0 failed to sync and 0 product(s) with missing reference(s)).","statistics":{"updated":0,"created":0,"failed":0,"processed":0,"latestBatchProcessingTimeInDays":0,"latestBatchProcessingTimeInHours":0,"latestBatchProcessingTimeInMinutes":0,"latestBatchProcessingTimeInSeconds":0,"latestBatchProcessingTimeInMillis":8,"latestBatchHumanReadableProcessingTime":"0d, 0h, 0m, 0s, 8ms","reportMessage":"Summary: 0 product(s) were processed in total (0 created, 0 updated, 0 failed to sync and 0 product(s) with missing reference(s)).","numberOfProductsWithMissingParents":0}}`

**Comment by lojzatran** [comment]
Hi @pramit-adhikari

Thanks for reporting the error.

To investigate further, can you share the product that causes this issue? If you cannot share it publicly, please create a support ticket: https://commercetools.atlassian.net/servicedesk/customer/portal/22/group/47/create/121

**Comment by pramit-adhikari** [comment]
Hi @lojzatran,

Before creating issue I have already created support task https://commercetools.atlassian.net/servicedesk/customer/portal/22/SUPPORT-22631. Can use same for product sample.

-- Pramit Adhikari

**Comment by salander85** [comment]
Hi @pramit-adhikari ,

thanks for your patience. This issue has been solved recently in version [commercetools-project-sync 5.4.2](https://github.com/commercetools/commercetools-project-sync/releases/tag/5.4.2).

Therefore i will close this ticket.
