### ISSUE TITLE
Error: Please provide valid client credentials using HTTP Basic Authentication

### ISSUE THREAD

**Issue by jafetsanchez** [commercetools/commercetools-project-sync#521]
I followed the instructions (such as adding environment variables, etc). Key, Client Id and Secret are correct for both source and target (triple checked)

1. Ran the command:

```
docker run \
-e SOURCE_PROJECT_KEY=xxxx \
-e SOURCE_CLIENT_ID=xxxx \
-e SOURCE_CLIENT_SECRET=xxxx \
-e TARGET_PROJECT_KEY=xxxx \
-e TARGET_CLIENT_ID=xxxx \
-e TARGET_CLIENT_SECRET=xxxx \
commercetools/commercetools-project-sync:5.4.0 -s all
```

2. Got this runtime error:

```
{
    "timestamp": "2023-11-06T17:37:03.847596Z",
    "severity": "ERROR",
    "loggerName": "com.commercetools.project.sync.CliRunner",
    "message": "Failed to run sync process.",
    "stackHash": "65e1f559",
    "stackTrace": "i.v.r.b.c.o.AuthException: detailMessage: Unauthorized\nhttp response formatted body: {\n  \"statusCode\" : 401,\n  \"message\" : \"Please provide valid client credentials using HTTP Basic Authentication.\",\n  \"errors\" : [ {\n    \"code\" : \"invalid_client\",\n    \"message\" : \"Please provide valid client credentials using HTTP Basic Authentication.\"\n  } ],\n  \"error\" : \"invalid_client\",\n  \"error_description\" : \"Please provide valid client credentials using HTTP Basic Authentication.\"\n}\nhttp response: io.vrap.rmf.base.client.ApiHttpResponse@27ed0b7a[statusCode=401,headers=[{key=access-control-allow-headers, value=Accept, Authorization, Content-Type, Origin, User-Agent, X-Correlation-ID}, {key=access-control-allow-methods, value=GET, POST, DELETE, OPTIONS}, {key=access-control-allow-origin, value=*}, {key=access-control-expose-headers, value=X-Correlation-ID}, {key=access-control-max-age, value=299}, {key=alt-svc, value=h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000}, {key=cache-control, value=no-store}, {key=content-type, value=application/json; charset=utf-8}, {key=date, value=Mon, 06 Nov 2023 17:37:03 GMT}, {key=pragma, value=no-cache}, {key=server, value=istio-envoy}, {key=server-timing, value=auth;dur=0}, {key=transfer-encoding, value=chunked}, {key=via, value=1.1 google}, {key=www-authenticate, value=Bearer realm=\"sphere\", error=\"invalid_client\", error_description=\"Please provide valid client credentials using HTTP Basic Authentication.\"}, {key=x-correlation-id, value=ct-training/34dc418a-7b95-4b58-9f63-6d3d171efb05}, {key=x-envoy-upstream-service-time, value=1}],textInterpretedBody={\"statusCode\":401,\"message\":\"Please provide valid client credentials using HTTP Basic Authentication.\",\"errors\":[{\"code\":\"invalid_client\",\"message\":\"Please provide valid client credentials using HTTP Basic Authentication.\"}],\"error\":\"invalid_client\",\"error_description\":\"Please provide valid client credentials using HTTP Basic Authentication.\"}]\nSDK: 17.1.0\nJava: 11.0.21\ncwd: /app\nrequest: <unknown>\n\n\tat i.v.r.b.c.o.BaseAuthTokenSuppli...\n"
}
```

**Note:** Again, the client id, secret, etc are correct. I created a separate test code using commercetools SDK and it worked correctly, so I don't think it is a credentials related issue.

Any pointers?

**Comment by lojzatran** [comment]
Hi @jafetsanchez 

Thank you for reporting the issue.

I tried the following command for my project and it is working:

```bash
docker run -e SOURCE_PROJECT_KEY=project-1 -e SOURCE_CLIENT_ID=jDvTHHHH-lR6FnQLhBBDxdHMB -e SOURCE_CLIENT_SECRET=F9yadfzrRhNmsdfGOlocpEoNokesvA9vv -e TARGET_PROJECT_KEY=project-2 -e TARGET_CLIENT_ID=tzjNb-0oprnIElxVfjksdjl -e TARGET_CLIENT_SECRET=0reweOI3IvkoLckOjoRjioerw commercetools/commercetools-project-sync:5.4.0 -s all
```

If problem persists, please create a support ticket https://commercetools.atlassian.net/servicedesk/customer/portals.

**Comment by xemayPurple** [comment]
Hi @lojzatran I have the same issue, getting the following error
```
{"timestamp":"2023-12-12T15:56:51.413191Z","severity":"INFO","loggerName":"commercetools.auth","message":"POST https://auth.europe-west1.gcp.commercetools.com/oauth/token 401"}
{"timestamp":"2023-12-12T15:56:51.466603Z","severity":"INFO","loggerName":"commercetools.auth","message":"POST https://auth.europe-west1.gcp.commercetools.com/oauth/token 401"}
```

But i'm passing the env variables 
`-e SOURCE_AUTH_URL="https://auth.us-central1.gcp.commercetools.com" \
-e SOURCE_API_URL="https://api.us-central1.gcp.commercetools.com" \`

I think the auth url is hardcoded to Europe https://github.com/commercetools/commercetools-project-sync/blob/master/src/main/java/com/commercetools/project/sync/util/CtpClientUtils.java#L63

**Comment by salander85** [comment]
Hi @xemayPurple ,

thanks for reporting this issue. 
You are right. At the moment it's only using the default values for the auth-url and api-url.
We will create an internal ticket to fix this.

**Comment by xemayPurple** [comment]
Thanks @salander85. 
Do you have an ETA to fix that?
This is blocking us to use this tool to copy data between projects

**Comment by nxverma** [comment]
any update , we are also facing same issue while running TF code .  Our creds are correct as working in Postman and other


Error: Post "https://api.us-central1.gcp.commercetools.com/<projectkey>/tax-categories": oauth2: "invalid_client" "Please provide valid client credentials using HTTP Basic Authentication."

**Comment by lojzatran** [comment]
Hi all,

This issue should be fixed and released: https://github.com/commercetools/commercetools-project-sync/pull/537.

I tested with the following command and it is working:
```
docker run -e SOURCE_PROJECT_KEY="your-source-project-key" -e SOURCE_CLIENT_ID="<clientid here>" -e SOURCE_CLIENT_SECRET="<client secret>" -e SOURCE_AUTH_URL="https://auth.us-central1.gcp.commercetools.com/oauth/token" -e SOURCE_API_URL="https://api.us-central1.gcp.commercetools.com" -e TARGET_PROJECT_KEY="your-target-project-key" -e TARGET_CLIENT_ID="<client id>" -e TARGET_CLIENT_SECRET="<client secret>" -e TARGET_AUTH_URL="https://auth.us-central1.gcp.commercetools.com/oauth/token" -e TARGET_API_URL="https://api.us-central1.gcp.commercetools.com" commercetools/commercetools-project-sync:5.4.4 -s all
```

**Comment by xemayPurple** [comment]
Hi @lojzatran this is still not fixed in this line https://github.com/commercetools/commercetools-project-sync/blob/master/src/main/java/com/commercetools/project/sync/util/CtpClientUtils.java#L63 is still getting the value from the europe region

**Comment by jenschude** [comment]
This is the default value. You have to set the environment variable for the auth and API url

**Comment by xemayPurple** [comment]
Ok, my bad, the issue with my in this case i was not adding the 
/oauth/token path to the api_auth url 
Thanks

**Comment by lojzatran** [comment]
Thank you for your feedback. I am closing this issue for now. If you have any further questions, feel free to reply to this issue.
