### ISSUE TITLE
Product images are not sync

### ISSUE THREAD

**Issue by xemayPurple** [commercetools/commercetools-project-sync#555]
Hi, when i sync the product data, the variant images are not sync between projects. 

Is any reason for that?

**Comment by lojzatran** [comment]
Hello @xemayPurple 

Thank you for reporting the issue.

I made a new release with a fix: https://github.com/commercetools/commercetools-project-sync/releases/tag/5.4.7.

I'm closing the issue now. If there are problems, you can reopen it.
