### ISSUE TITLE
Standalone prices sync support

### ISSUE THREAD

**Issue by igor-tereshchenko** [commercetools/commercetools-project-sync#556]
Hi, are there any plans for supporting standalone prices sync between projects? If so, any possible timelines you can share?
Thank you.

**Comment by anjaliVashisth** [comment]
Hi @igor-tereshchenko,
Thank you for reaching out.
Yes, currently we don't provide support for standalone prices.
However, please feel free to create a support ticket for adding the support of standalone prices here, https://support.commercetools.com/
Thank you.

**Comment by lojzatran** [comment]
I am hereby closing this issue.
