### ISSUE TITLE
filter customobjects with query params

### ISSUE THREAD

**Issue by kkattaexp** [commercetools/commercetools-project-sync#570]
Is there a way to filter customobjects sync with containername or key just like we do with --productQueryParameters for products

**Comment by lojzatran** [comment]
Hi @kkattaexp 

Thank you for reaching out.

Currently there is no way to filter customobjects sync.
However, please feel free to create a support ticket for adding the support here: https://support.commercetools.com/

**Comment by kkattaexp** [comment]
Ok Sure, Thank you @lojzatran
