### ISSUE TITLE
Is it possible to use this syncer as a library in springboot project 

### ISSUE THREAD

**Issue by artofvijay** [commercetools/commercetools-project-sync#606]
Instead of docker container is it possible to use this as library to use with springboot web application. Like I will have ui for  entering source and destination project, from springboot service class trigger this syncer

**Comment by lojzatran** [comment]
Hi @artofvijay,

If you are interested in a library, please use this one: https://github.com/commercetools/commercetools-sync-java. 

`project-sync` adds a command-line interface for this library and also ensures syncing from project to project. This will need to be done by you or you can call `project-sync` from your springboot web app this tool in the command line.

**Comment by artofvijay** [comment]
Thank you for your recommendation.
