### ISSUE TITLE
Return non-zero exit code when synchronisation fails

### ISSUE THREAD

**Issue by tomwscott** [commercetools/commercetools-project-sync#82]
The project sync can fail for a variety of reasons e.g. API Client with invalid scope etc. I would like to run the synchronisation as a scheduled job in a docker container and be notified if it fails. 

The process currently returns a zero status code regardless of whether it ran successfully or not which hides whether or not the synchronisation was _actually_ successful.

**Comment by butenkor** [comment]
Thanks for reporting it. Depending on logging provider you use, until it is fixed you could also set up an inactivity alert which filters by message produced here: https://github.com/commercetools/commercetools-project-sync/blob/f1f5d64a064bd73a52b6f5c865dd1294c39300c8/src/main/java/com/commercetools/project/sync/Syncer.java#L137

You could also provide a PR :)

**Comment by praveenkumarct** [comment]
We realised that non-zero error code should only occur when the application exits unexpectedly or application crashes. 
Invalid API client is just a wrong configuration which depending on scopes, might be successful for products but not for categories, In this case application will sync products and error will be rendered for categories.
